name: Android CI

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create KeyStore File and Properties
      run: mkdir ./app/signing
    - name: pp
      env: 
        STORE_PASSWORD: $
      run: 
        echo "print 22"
        ehco "KEY_PASSWORD=$KEY_PASSWORD"
        ehco "STORE_PASSWORD=$STORE_PASSWORD"
      
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build
      
            
